// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5FOyf8eBqPwYFygeIzAgGmgLZnAy-3PE',
    appId: '1:411058786400:web:011348712daa26bceb7305',
    messagingSenderId: '411058786400',
    projectId: 'rizz-7e0b8',
    authDomain: 'rizz-7e0b8.firebaseapp.com',
    storageBucket: 'rizz-7e0b8.firebasestorage.app',
    measurementId: 'G-XM1XC41ZYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD45t-oQ-Ob9oPqPylLkB1IjcM_VEMYaxA',
    appId: '1:411058786400:android:f849f56161d8fa7deb7305',
    messagingSenderId: '411058786400',
    projectId: 'rizz-7e0b8',
    storageBucket: 'rizz-7e0b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59-HFORHs-kW3qlGvms6vjixyfHdOgb0',
    appId: '1:411058786400:ios:95f4eee426c58549eb7305',
    messagingSenderId: '411058786400',
    projectId: 'rizz-7e0b8',
    storageBucket: 'rizz-7e0b8.firebasestorage.app',
    androidClientId: '411058786400-4bn2qqisigik72kbftj134kd4mj7pdoc.apps.googleusercontent.com',
    iosClientId: '411058786400-o4juakuuer3m55hlf3i5v977kd4dmdmr.apps.googleusercontent.com',
    iosBundleId: 'com.inspira.rizzApp',
  );
}
